### ISSUE TITLE
US 1 - Homepage

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#1]

**Comment by landaluis** [comment]
## Homepage
## Value proposition
As an User
I want a Homepage
So i can get an overview from the app
## Description
![Image](https://user-images.githubusercontent.com/122018061/222694618-32c83b7b-6e1c-4861-8dfe-d504cd274d04.png)

## Acceptance criteria
- [ ] The name of the app is at the top (fixed). 
- [ ] There is a short Welcome message, as long any card appears. 
- [ ] This message tells you how you can create your first card.
- [ ] There is a bottom navigation bar (fixed), which had 4 buttons (add Card, add Ticket, all Cards, profile)
## Tasks
- [ ] Create a top bar fixed that shows the name of the app 
- [ ] Create a bottom navigation bar with  4 buttons (add Card, add Ticket, all Cards, profile)  
- [ ] Create a custom welcome message in the shape of a card, that Welcomes you and
      tells you how to create your first card.

**Comment by pung-one** [comment]
top!

**Comment by landaluis** [comment]
danke!
