### ISSUE TITLE
Display a Card (2/2)

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#10]
## Value Proposition

As an User
I want to see the info of my new Card
So i can have an overview of my wish.

## Description

​
![Display a Card (2:2)](https://user-images.githubusercontent.com/122018061/224274491-a85d34b4-c5df-442b-8a84-01a1420b735e.png)

## Acceptance Criteria

- [ ] The second part (2/2) shows: the name, description, price and the next saving date.  
- [ ]  Shows a progression bar with two % sides: left side(my savings), right side (Needed).
- [ ]  Down the progression bar: the values from the left and right side in numbers with their
       names. 
- [ ] Shows two buttons: Edit Card and Delete Card.
- [ ] Down the Card shows a "Recent Activity" list with the date and amount of money ​

## Tasks

- [ ] Create the Card info component.  
- [ ] Create the Progress bar component. ​
- [ ] Create the Edit and Delete button.
- [ ] Create the recent activity component.
