### ISSUE TITLE
US 6 - Profile page 

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#11]
## Value Proposition

As an User
I want to see my Profile page
So i can have my name and a summary of my cards

## Description

![Profile Page](https://user-images.githubusercontent.com/122018061/224276086-036433df-a326-4031-8bb3-a90ec1d4b6e0.png)

​

## Acceptance Criteria

- [ ]   Shows a profile pic, name, and a summary from my cards (actives, golden and platinum) 
 - [ ]  Shows a back button and an edit profile button.​

## Tasks
- [ ] Create the Profile component .  
- [ ] Create the summary components (active, golden, platinum)  
- [ ] Create the edit profile component.  ​
