### ISSUE TITLE
US 7 - Golden  Card 

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#16]
## Golden Card

As an User 
​I want to see my Card turn golden
So i can have an output that i have reach my goal

## Description

Left Image
​
![Golden Card](https://user-images.githubusercontent.com/122018061/227527195-af0caced-97c1-4e2d-8aa6-b3aade017f90.png)

## Acceptance Criteria

- [ ]  Card turn to gold when price = savings . 
- [ ]  Show "Golden" counter in profile page.
- [ ]  Show new Display in info section
      ​

## Tasks

- [ ] Create a conditional background Styling. 
- [ ] Add "Golden" counter to the profile Page.
- [ ] Restructuring the info section from golden cards.
      ​
