### ISSUE TITLE
US 8 - Platinum Card

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#18]
## Platinum

As a user 
I want to see my new state of my card
so i can be sure i reach my goal.
​

## Description
![PlatinumCard](https://user-images.githubusercontent.com/122018061/228488658-8417493d-dac0-4833-868a-cad3fe76b37f.png)

​

## Acceptance Criteria

- [ ] Card turn to platinum when upload a new picture.
- [ ] Show "Platinum" counter in profile page.
- [ ] Show new display in the info section.
      ​

## Tasks

- [ ] Create a conditional background Styling. 
- [ ] Add "Platinum" counter to the profile Page.
- [ ]  Restructuring the info section from platinum cards.
      ​
