### ISSUE TITLE
User Story 1 - Create a new Card

### ISSUE THREAD

**Issue by landaluis** [landaluis/Capstone-Project#2]
## Value proposition
As an User
I want to create a new Card
So i can have my first Wish Card or as many as i want
## Description
![CreateNewCard](https://user-images.githubusercontent.com/122018061/222679166-b25330c5-c130-4ac9-af62-6abbd57922d9.png)
## Acceptance criteria
- [ ] The "Form" from the Card should have these fields :
      Name of the Article(Wanted), Description(Why), Price, Periodicity(days, weeks, months),
      a field for insert photo(URL), a Reset button and a Submit button.   
- [ ] After you click the submit button, a message appears "You have create a new Card" and 
      reset the Form
-[ ] The Form page shows an exit button, that takes you to the overview (Cards page) page.
## Tasks
- [ ] Create a Form Component whit the listed fields.   
- [ ] Create the Exit  button Component.  
- [ ] Create Reset  button Component.  
- [ ] Create the Create Card button Component.
