### ISSUE TITLE
US2-Create a new Card 

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#2]
## Homepage

As an User
I want a Homepage
So i can get an overview from the app

## Description
![Homepage](https://user-images.githubusercontent.com/122018061/222693654-c73cb536-59ab-4bad-a9db-f14f2c412502.png)
## Acceptance criteria
- [ ] The name of the app is at the top (fixed). 
- [ ] There is a short Welcome message, as long any card appears. 
- [ ] This message tells you how you can create your first card.
- [ ] There is a bottom navigation bar (fixed), which had 4 buttons (add Card, add Ticket, all Cards, profile).

## Tasks
- [ ] Create a top bar fixed that shows the name of the app 
- [ ] Create a bottom navigation bar with  4 buttons (add Card, add Ticket, all Cards, profile)  
- [ ] Create a custom welcome message in the shape of a card, that Welcomes you and
      tells you how to create your first card.
