### ISSUE TITLE
US 9 - About Info

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#20]
## Value Proposition

As an User
I want to see an About page, 
So i can read a little bit more about the app.

## Description
![AboutInfo](https://user-images.githubusercontent.com/122018061/228510528-9e6357a1-8107-4592-8855-cbd2cadfb754.png)

​

​

## Acceptance Criteria

- [ ]  in Home page, shows in the right up corner a "?" as a button.  
- [ ]  After i click shows me a window with the About info.  

      ​

## Tasks

- [ ] Create the component About  
- [ ] Set the button in the Home page.  

      ​
