### ISSUE TITLE
US 2 - Create a new card

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#3]

**Comment by landaluis** [comment]
## Create a new Card
## Value proposition
As an User
I want to create a new Card
So i can have my first Wish Card or as many as i want
## Description


![Image](https://user-images.githubusercontent.com/122018061/222696083-35a6866e-61e8-4ba0-9631-659a74cff8f5.png)

## Acceptance criteria
- [ ] The "Form" from the Card should have these fields :
      Name of the Article(Wanted), Description(Why), Price, Periodicity(days, weeks, months),
      a field for insert photo(URL), a Reset button and a Submit button.   
- [ ] After you click the submit button, a message appears "You have create a new Card" and 
      reset the Form
-[ ] The Form page shows an exit button, that takes you to the overview (Cards page) page.
## Tasks
- [ ] Create a Form Component whit the listed fields.   
- [ ] Create the Exit Component.  
- [ ] Create the Reset Component.  
- [ ] Create the Create Card Component.
