### ISSUE TITLE
US 3 - Buy a Ticket

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#4]

**Comment by landaluis** [comment]
## Buy a Ticket 
## Value proposition
As an User
I want to create a buy a new Ticket (when you have a Ticket, you can applied it to a Card, to decrease
the amount of money that the user need to reach his goal).
So i can have an extra Saving option when i receive extra money for my wish.
## Description


![Image](https://user-images.githubusercontent.com/122018061/222699624-c377c95d-9eee-4041-a91a-14c4a5389646.png)

## Acceptance criteria
- [ ] Should display a Form with the Value field and a submit button (Buy a Ticket).   
- [ ] When i click the submit button it should appear a message "You have a new Ticket",
      reset the Form and show it down.   
- [ ] The tickets had a value field and a [x] button in case i want to delete it. The other way to delete a 
      ticket is using it in a card. (Hover effect?)
## Tasks
- [ ] Create the component "Buy a Ticket" (value field) and a submit button.    
- [ ] - [ ] Create a delete button like a [x] to delete a ticket (a confirmation message should appear).

**Comment by pung-one** [comment]
good!
