### ISSUE TITLE
US 4 - Create a new card (1/2)

### ISSUE THREAD

**Issue by landaluis** [landaluis/capstone-project#5]

**Comment by landaluis** [comment]
## Display a Card (1/2)
## Value proposition
As an User
I want to see my new Card
So i can have all the info that i already submit in my card.
## Description


![Image](https://user-images.githubusercontent.com/122018061/222714410-9ad63b9a-aa0a-45e9-a5d1-6caba80b8b07.png)

## Acceptance criteria
- [ ] The Card format had 2 parts, the first part (1/2) shows two squares:
first square shows the photo and the name of the "Wish".  
- [ ] The second square shows a vertical progressive bar in the shape of an egg and the date 
      of the card creation (Birthday) 
- [ ] On the right side of the card there are an id number and 3 buttons (info button, 
        ticket button and a "collect saving" button. 
- [ ] The collect saving button update the "saving count". It activates (green) every time the periodicity
       time start again and turns grey after the button is clicked.
## Tasks
- [ ] Create a card with the above description.  
- [ ] Place in position the 3 buttons and the id number area.  
- [ ] Create the connection between the Ticket button and the ticket page and implement the
      function .
  - [ ] The id number component will generate a new id each time a new card is created.
  - [ ] Create the "collect saving" button (€) component and functionality.

**Comment by pung-one** [comment]
LGTM

**Comment by landaluis** [comment]
thanks!
